name: Redirect Pull Requests to dev and Merge

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  redirect-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is targeting main
        id: check_target_branch
        run: |
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            echo "is_main=true" >> $GITHUB_ENV
          else
            echo "is_main=false" >> $GITHUB_ENV
          fi
      - name: Redirect to dev branch
        if: env.is_main == 'true'
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          curl -s -X PATCH \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/pulls/$PR_NUMBER \
            -d '{"base":"dev"}'

      - name: Auto-merge into dev branch
        if: env.is_main == 'true'
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN }}
          script: |
            const prNumber = parseInt(process.env.PR_NUMBER, 10);
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });
            
            if (pullRequest.base.ref === "dev") {
              await github.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
              });
              console.log(`PR #${prNumber} has been successfully merged into dev.`);
            } else {
              console.log(`PR #${prNumber} was not redirected to dev.`);
            }
