# .github/workflows/redirect-pr-to-dev.yml
name: Redirect PR to Dev

on:
  pull_request:
    types: [opened, reopened]

jobs:
  redirect-pr-to-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR targets main
        if: github.event.pull_request.base.ref == 'main'
        run: |
          # Close the original PR to main
          gh pr close ${{ github.event.pull_request.number }}

          # Recreate a new PR to the 'dev' branch with the same title and body
          gh pr create --head "${{ github.event.pull_request.head.ref }}" --base "dev" --title "${{ github.event.pull_request.title }}" --body "${{ github.event.pull_request.body }}"
          
          echo "Closed PR to 'main' and recreated it targeting 'dev'."
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
